// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdvancedDateFieldController from "./advanced_date_field_controller"
application.register("advanced-date-field", AdvancedDateFieldController)

import CompletableFieldController from "./completable_field_controller"
application.register("completable-field", CompletableFieldController)

import FamilyTreeController from "./family_tree_controller"
application.register("family-tree", FamilyTreeController)

import PersonFieldController from "./person_field_controller"
application.register("person-field", PersonFieldController)

import PersonTagListFieldController from "./person_tag_list_field_controller"
application.register("person-tag-list-field", PersonTagListFieldController)

import TagListFieldController from "./tag_list_field_controller"
application.register("tag-list-field", TagListFieldController)
