require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/FrozenStringLiteralComment:
  Enabled: false
