services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/ruby:3
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    # Runs app on the same network as the database container,
    # allows "forwardPorts" in devcontainer.json function.
    network_mode: service:valkey
    depends_on:
      - valkey
    volumes:
      # Mounts the project folder to '/workspaces/geneac'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/workspaces/geneac:cached

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  valkey:
    image: valkey/valkey:8-alpine
    command: valkey-server --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - valkey-data:/data
    environment:
      MYSQL_ROOT_PASSWORD: blis123

volumes:
  valkey-data: