#!/bin/bash

CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REGION="us-east-2"
CFN="$CURDIR/geneac-aws.yml"

function validate_cfn {

  if cfn-lint "$CFN" ; then
    echo -e "Validated CloudFormation."
  else
    echo -e "CloudFormation Validation failed."
    exit 1
  fi
}

function do_deploy {
  STAGE="$1"
  HOSTNAMES="$2"

  printf "Deploying CloudFormation changeset [%s]...", "$STAGE"

  aws cloudformation deploy \
      --region "$REGION" \
      --stack-name "$STAGE" \
      --capabilities CAPABILITY_IAM \
      --parameter-overrides="Hostnames=$HOSTNAMES" \
      --template-file "$CFN"
}

validate_cfn
echo "----------"
do_deploy "geneac-beta" "https://geneac-beta.herokuapp.com"
echo "----------"
do_deploy "geneac-prod" "https://geneac.herokuapp.com"
echo "----------"
