name: Brakeman

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  brakeman:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Brakeman
      uses: devmasx/brakeman-linter-action@35a5a3de5330fead60055f952a90cc324fd68295
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
