name: Lint changes

on:
  workflow_dispatch:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.1.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install linters
        run: |
          pip3 install cfn-lint
          npm install -g markdownlint-cli
      - name: Run script/lint.rb
        run: |
          script/lint.rb
