name: Lint changes

on:
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - name: Install linters
        run: |
          npm install -g markdownlint-cli
      - name: Run script/lint.rb
        run: script/lint.rb
