name: RSpec Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.1.1'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM modules
        run: bin/yarn install

      - name: Build App
        run: |
          mv config/database.cicd.yml config/database.yml
          bin/rails db:setup
          bin/rails webpacker:compile

      - name: Run Tests
        run: |
          bundle exec rspec
